---
title: "EC499"
author: "Yuxuan Liu"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
---
```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = 'center')
library(tidyverse)
library(skimr)
library(data.table)
library(ggplot2)
library(tibble)
rmse = function(actual, predicted) {
  sqrt(mean((actual - predicted) ^ 2))
}
get_complexity = function(model) {
  length(coef(model)) - 1
}
get_rmse = function(model, data, response) {
  rmse(actual = subset(data, select = response, drop = TRUE),
       predicted = predict(model, data))
}
library(readr)
library(broom)
library(stargazer)
data <- read_csv("C:/Users/lyx48/OneDrive/桌面/EC499/DataSet.csv")

```

## 1. the abstract of the essay

```{r part1}
com <- list()
rms <- list()

fit_0 <- lm(data$TotalCapitalOutlays~data$Income)
com0 <-get_complexity(fit_0)
rm0 <- rmse(actual = data$TotalCapitalOutlays, predicted = predict(fit_0, data))
summary(fit_0)
com <- append(com,com0)
rms <- append(rms,rm0)

fit_1 <- lm(data$TotalCapitalOutlays~data$`PopualtionDensity`)
com1 <-get_complexity(fit_1)
rm1 <- rmse(actual = data$TotalCapitalOutlays, predicted = predict(fit_1, data))
summary(fit_1)

fit_2 <- lm(data$TotalCapitalOutlays~data$`Politicalscore`)
com2 <-get_complexity(fit_2)
rm2 <- rmse(actual = data$TotalCapitalOutlays, predicted = predict(fit_2, data))
summary(fit_2)

fit_3 <- lm(data$TotalCapitalOutlays~data$Precipitation)
com3 <-get_complexity(fit_3)
rm3 <- rmse(actual = data$TotalCapitalOutlays, predicted = predict(fit_3, data))
summary(fit_3)

```

```{r part2}
fit_4 <- lm(data$TotalCapitalOutlays~data$Income+data$`PopualtionDensity`)
com4 <-get_complexity(fit_4)
rm4 <- rmse(actual = data$TotalCapitalOutlays, predicted = predict(fit_4, data))
summary(fit_4)
com <- append(com,com4)
rms <- append(rms,rm4)


fit_5 <- lm(data$TotalCapitalOutlays~data$Income+data$`PopualtionDensity`+data$`Politicalscore`)
com5 <-get_complexity(fit_5)
rm5 <- rmse(actual = data$TotalCapitalOutlays, predicted = predict(fit_5, data))
summary(fit_5)
com <- append(com,com5)
rms <- append(rms,rm5)


fit_6 <- lm(data$TotalCapitalOutlays~data$Income+data$`PopualtionDensity`+data$`Politicalscore`+data$Precipitation)
com6 <-get_complexity(fit_6)
rm6 <- rmse(actual = data$TotalCapitalOutlays, predicted = predict(fit_6, data))
summary(fit_6)
com <- append(com,com6)
rms <- append(rms,rm6)
```



```{r  part1 plot1}
ggplot(data)+geom_smooth(aes(y=data$Income,x=data$TotalCapitalOutlays))+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_fill_distiller(palette = "Blues")
```

```{r  part1 plot2}
re5 <- resid(fit_5)
fit5 <- fitted(fit_5)
ggplot(data)+geom_smooth(aes(y=data$Precipitation,x=data$TotalCapitalOutlays))+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_fill_distiller(palette = "Blues")
```


```{r  part1 plot2, height=12,fig.width=12,echo=FALSE}
ggplot(data)+geom_smooth(aes(y=PopualtionDensity,x=TotalCapitalOutlays))+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_fill_distiller(palette = "Blues")
```
```{r part2 plot4}
ggplot(data)+geom_smooth(aes(y=Politicalscore ,x=TotalCapitalOutlays))+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+scale_fill_distiller(palette = "Blues")
```
```{r table1}
max_min <- as_tibble(data[which.max(data$PopualtionDensity),])
max_min2  <- rbind(max_min,data[which.min(data$PopualtionDensity),])
max_min3  <- rbind(max_min2,data[which.max(data$Income),])
max_min4  <- rbind(max_min3,data[which.min(data$Income),])
max_min5  <- rbind(max_min4,data[which.max(data$Politicalscore),])
max_min6 <- rbind(max_min5,data[which.min(data$Politicalscore),])
max_min7  <- rbind(max_min6,data[which.max(data$Precipitation),])
max_min8  <- rbind(max_min7,data[which.min(data$Precipitation),])
 
Max_min =c("Max Popualtion Density","Min Popualtion Density","Max Income","Min Income","Max Political Score","Min Political Score","Max Precipitation","Min Precipitation")
con <- cbind(max_min8,Max_min)
```

```{r table2}
table <- data.frame(Predictor=rep(c("Income","Precipitation","Popualtion Density","Politicalscore"), each=1),
                    Explain=rep(c("Average Income of each state from 2015 to 2020","Average Precipitation in each state from 2015 to 2020","Average Each state popualtion divided the Population size through 2015 to 2020","Political Trend for each state from 2015 to 2020"), each=1))

```

```{r table3}
table4 <- subset(data, select = c("State", "TotalCapitalOutlays"))

```


```{r part2 }·
stda <- map2_dfr(com, rms, ~ tibble(Complexity = .x, RMSE = .y))
plot(RMSE ~ Complexity, stda)
```
 


#### Seperate the data into 2 parts to make a more detailed test
```{r part2 }

set.seed(7)
num_obs = nrow(data)

train_index = sample(num_obs, size = trunc(0.50 * num_obs))
train_data = data[train_index, ]
test_data = data[-train_index, ]

fit0 <- lm(data$TotalCapitalOutlays~data$Income)
get_rmse(model = fit_4, data = train_data, response = "TotalCapitalOutlays")
get_rmse(model = fit_4, data = test_data, response = "TotalCapitalOutlays")

fit1 <- lm(data$TotalCapitalOutlays~data$Income+data$PopualtionDensity)
get_rmse(model = fit_5, data = train_data, response = "TotalCapitalOutlays")
get_rmse(model = fit_5, data = test_data, response = "TotalCapitalOutlays")

fit2 <- lm(data$TotalCapitalOutlays~data$Income+data$PopualtionDensity+data$Politicalscore)
get_rmse(model = fit_6, data = train_data, response = "TotalCapitalOutlays")
get_rmse(model = fit_6, data = test_data, response = "TotalCapitalOutlays")

fit3 <- lm(data$TotalCapitalOutlays~data$Income+data$PopualtionDensity+data$Politicalscore+data$Precipitation)
get_rmse(model = fit3, data = train_data, response = "TotalCapitalOutlays")
get_rmse(model = fit3, data = test_data, response = "TotalCapitalOutlays")

model_list = list(fit0, fit1, fit2, fit3)

train_rmse = sapply(model_list, get_rmse, data = train_data, response = "TotalCapitalOutlays")
test_rmse = sapply(model_list, get_rmse, data = test_data, response = "TotalCapitalOutlays")
model_complexity = sapply(model_list, get_complexity)
```




The rest of your answer to the first question.

\newpage
## Create a table to show the result
```{r q2}
table <- data.frame(Model=rep(c("LM4","LM5","Fit2","Fit3"), each=1),
                    train_rmse,test_rmse,Predictors=rep(c("Income","Income,Population","Income,Population,Size of Area","Income,Population,Size of Area,Average Temperature"), each=1))
print(table)
```


                                                                                                                                                                                                                                               